### ISSUE TITLE
Complete accounting apps for Canada

### ISSUE THREAD

**Issue by max3903** [OCA/l10n-canada#18]
# l10n_ca_account_profile

This module provides all the dependencies, data, translations and configuration to have OpenERP as an accounting software ready for canadians accountants and equivalent to local solutions like Acomba, Simply Accounting, Avantage or Quickbooks.
# Repositories
- git https://github.com/OCA/l10n-canada.git 7.0
- git https://github.com/OCA/webkit-tools.git 7.0
- git https://github.com/OCA/account-financial-reporting.git 7.0
- git https://github.com/OCA/account-financial-tools.git 7.0
- git https://github.com/OCA/account-payment.git 7.0
- git https://github.com/OCA/account-invoicing.git 7.0
- git https://github.com/OCA/bank-statement-reconcile.git 7.0
- git https://github.com/savoirfairelinux/account-invoice-reporting.git 7.0-partner-aging-with-changes
- git https://github.com/savoirfairelinux/banking.git 7.0-npg_account_make_deposit
- git https://github.com/savoirfairelinux/banking.git 7.0-npg_bank_account_reconciliation
# Dependencies
- l10n_ca_toponyms
- currency_rate_update
- report_xls
- account_financial_report_webkit
- account_financial_report_webkit_xls
- account_journal_report_xls
- account_move_line_report_xls
- account_chart_report
- account_reversal
- partner_aging
- npg_account_make_deposit
- npg_bank_account_reconciliation
- account_statement_base_import
- account_invoice_merge
- account_voucher_supplier_invoice_number
- A module to compare total and sum of lines on a voucher
# Accounting configuration panel

Add a section "Canada" with options to:
- [x] Allow canadian checks printing (l10n_ca_account_check_writing, res_currency_print_on_check )
- [x] Import bank statements (l10n_ca_account_statement_import). List of banks (l10n_ca_account_statement_import_*) :
  - [ ] Bank of Montreal (BMO)
  - [ ] Canadian Imperial Bank of Commerce (CIBC)
  - [ ] Desjardins (DESJ)
  - [ ] Laurentian Bank (LB)
  - [ ] National Bank of Canada (NBC)
  - [ ] Royal Bank of Canada (RBC)
  - [x] Toronto Dominium (TD) : #41 
  - [ ] Scotia Bank (SB)
- [ ] Install the fiscal position rules module based on the company province:
  - [ ] l10n_ca_ab_account_fiscal_position_rule
  - [ ] l10n_ca_bc_account_fiscal_position_rule
  - [ ] l10n_ca_mb_account_fiscal_position_rule
  - [ ] l10n_ca_nb_account_fiscal_position_rule
  - [ ] l10n_ca_nl_account_fiscal_position_rule
  - [ ] l10n_ca_nt_account_fiscal_position_rule
  - [ ] l10n_ca_nu_account_fiscal_position_rule
  - [ ] l10n_ca_nv_account_fiscal_position_rule
  - [ ] l10n_ca_on_account_fiscal_position_rule
  - [ ] l10n_ca_pe_account_fiscal_position_rule
  - [x] l10n_ca_qc_account_fiscal_position_rule
  - [ ] l10n_ca_sk_account_fiscal_position_rule
  - [ ] l10n_ca_yt_account_fiscal_position_rule
# HR configuration panel

Add a section "Canada" with options to:
- [ ] Install Payroll (l10n_ca_hr_payroll) : #43. Dropdown list of provinces to install the provincial rules:
  - [ ] l10n_ca_ab_hr_payroll
  - [ ] l10n_ca_bc_hr_payroll
  - [ ] l10n_ca_mb_hr_payroll
  - [ ] l10n_ca_nb_hr_payroll
  - [ ] l10n_ca_nl_hr_payroll
  - [ ] l10n_ca_nt_hr_payroll
  - [ ] l10n_ca_nu_hr_payroll
  - [ ] l10n_ca_nv_hr_payroll
  - [ ] l10n_ca_on_hr_payroll
  - [ ] l10n_ca_pe_hr_payroll
  - [ ] l10n_ca_qc_hr_payroll : #45
  - [ ] l10n_ca_sk_hr_payroll
  - [ ] l10n_ca_yt_hr_payroll
- [ ] Install Payroll Accounting (l10n_ca_hr_payroll_account). Dropdown list of provinces to install the provincial rules:
  - [ ] l10n_ca_ab_hr_payroll_account
  - [ ] l10n_ca_bc_hr_payroll_account
  - [ ] l10n_ca_mb_hr_payroll_account
  - [ ] l10n_ca_nb_hr_payroll_account
  - [ ] l10n_ca_nl_hr_payroll_account
  - [ ] l10n_ca_nt_hr_payroll_account
  - [ ] l10n_ca_nu_hr_payroll_account
  - [ ] l10n_ca_nv_hr_payroll_account
  - [ ] l10n_ca_on_hr_payroll_account
  - [ ] l10n_ca_pe_hr_payroll_account
  - [ ] l10n_ca_qc_hr_payroll_account
  - [ ] l10n_ca_sk_hr_payroll_account
  - [ ] l10n_ca_yt_hr_payroll_account

Copied from:
https://blueprints.launchpad.net/openerp-canada/+spec/l10n-ca-account-profile

**Comment by JordiBForgeFlow** [comment]
@max3903 I'm also using npg_bank_account_reconciliation for the US. I'd like to migrate the module to the OCA. Would you agree to rename it to "bank_statement_audit"? I'm not sure what would be the implications of renaming the module with respect to existing installations? I guess that some sort of migration would need to occur, right?

**Comment by max3903** [comment]
@jbeficent I am currently talking with NPG and helping them contributing their modules. I would like to rename it bank_account_reconciliation and yes, it would require some migration.

**Comment by JordiBForgeFlow** [comment]
@max3903 Ok, thanks!
