### ISSUE TITLE
Quebec Payroll

### ISSUE THREAD

**Issue by max3903** [OCA/l10n-canada#54]
- [x] l10n_canada rename column in module res_partner_attributes_add_SIN : #53
- [x] Payroll modules in HR : https://github.com/OCA/hr/issues/74
- [ ] Improve Quebec Payroll : #45
- [ ] Improve Canada Payroll : #43 
- [x] Update the canadian chart of accounts : https://github.com/odoo/odoo/pull/5351
- [ ] Quebec Payroll Accounting : #57 
- [ ] Canada Payroll Accounting : #56 
- [x] Documentation : https://www.odoo.com/forum/help-1/question/payroll-for-quebec-canada-74450
- [x] Demo available on https://payroll.erp.sflx.ca

**Comment by max3903** [comment]
ping @dufresnedavid

**Comment by ghost** [comment]
@max3903 Update the canadian chart of accounts : odoo/odoo#5351 is done
