### ISSUE TITLE
Migration to version 8.0

### ISSUE THREAD

**Issue by max3903** [OCA/l10n-canada#55]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-8
# Modules to migrate
- [ ] account_statement_td_canada_import
- [ ] account_tax_expense_include by @joaoalf in #72 
- [ ] hr_expense_line_supplier
- [x] l10n_ca_account_check_writing by @veloutin in #33 
- [ ] l10n_ca_account_profile
- [ ] l10n_ca_hr_employee_benefits
- [ ] l10n_ca_hr_income_tax_deductions
- [ ] l10n_ca_hr_payroll
- [ ] l10n_ca_hr_payroll_account
- [ ] l10n_ca_qc_account_fiscal_position_rule @ehtaga in #71
- [ ] l10n_ca_qc_hr_payroll
- [ ] l10n_ca_qc_hr_payroll_account
- [x] l10n_ca_toponyms by @max3903 in #13 
- [x] res_currency_print_on_check by @Jehog in #52 
- [x] res_partner_attributes_add_BN by @ehtaga in #63 
- [x] res_partner_attributes_add_NEQ by @ehtaga in #64 
- [x] res_partner_attributes_add_SIN by @ehtaga in #62

**Comment by whotopia** [comment]
Hi,   
Was wondering if this work was ever completed anywhere for Odoo8 ???

Thanks
S
