### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-canada#75]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] l10n_ca_toponyms
- [x] res_partner_attributes_add_SIN
- [x] res_partner_attributes_add_BN
- [x] res_partner_attributes_add_NEQ
## Accounting
- [ ] res_currency_print_on_check
- [ ] l10n_ca_account_check_writing
- [ ] l10n_ca_qc_account_fiscal_position_rule
- [ ] l10n_ca_account_profile (#81)
## Payroll
- [ ] l10n_ca_hr_payroll
- [ ] l10n_ca_hr_payroll_account
- [ ] l10n_ca_qc_hr_payroll
- [ ] l10n_ca_qc_hr_payroll_account
## Expenses
- [ ] hr_expense_line_supplier
- [ ] account_tax_expense_include

**Comment by max3903** [comment]
We estimated the effort to migrate:
- l10n_ca_hr_payroll
- l10n_ca_hr_payroll_account
- and their dependencies available in https://github.com/OCA/hr/issues/157

to 10 days.

Please comment below (or send a mail to contact@savoirfairelinux.com) if you are interested to finance it.
