### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-canada#87]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] account_tax_expense_include_unported
- [ ] hr_expense_line_supplier_unported
- [ ] l10n_ca_account_check_writing
- [ ] l10n_ca_hr_payroll
- [ ] l10n_ca_hr_payroll_account
- [ ] l10n_ca_qc_account_fiscal_position_rule_unported
- [ ] l10n_ca_qc_hr_payroll
- [ ] l10n_ca_qc_hr_payroll_account
- [ ] l10n_ca_toponyms
- [ ] res_currency_print_on_check
- [ ] res_partner_attributes_add_BN
- [ ] res_partner_attributes_add_NEQ
- [ ] res_partner_attributes_add_SIN
